/**:
  ros__parameters:

    motion_planning:
      planning_time: 5.0
      planning_attempts: 10
      max_velocity_scaling_factor: 0.1
      max_acceleration_scaling_factor: 0.1
      planner_id: "RRTConnect"

    target_tolerance:
      position: 0.001
      orientation: 0.01
      joint: 0.01

    tf:
      timeout: 0.1
      cache_duration: 10.0

    decartes:
      eef_step: 0.01
      jump_threshold: 0.0
      vel_scale: 0.1
      acc_scale: 0.1
      min_success_rate: 0.8